project:
  type: website
  output-dir: docs

website:
  title: "Oksana Protsukha"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: posts.qmd
        text: Projects
      - href: resources.qmd
        text: Resources

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    page-layout: full

editor: visual


